repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.2'  # Use the latest version
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-install  # Optional: ensures locked packages are installed locally
