"""create users, orders, order_items tables

Revision ID: 72a2faac9c6a
Revises:
Create Date: 2026-04-29 02:24:29.554592

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "72a2faac9c6a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
